### ISSUE TITLE
[mic step 2] overview

### ISSUE THREAD

**Issue by sirspock** [mintproject/mic#133]
## Pipeline

1.  **The user must run the code**
Example
```
mic encapsulate step2 --trace python code.py
```

2   If the execution is ok, **The user must run type:** 
$ mic encapsulate step2 --extract

3. MIC is going to read the reprozip configuration file and obtain:
   1. Inputs directory and file
   2. Code
   3. Outputs
   4. Invocation line
   5. Working dir
   6. Run the detection again `pip_requeriments` and `conda_environment`
   7. Parameters in the invocation

   

Issues:

- [x] Create the step2 no arguments
    1. Option 1: trace: call to reprozip trace

- [x] Add instruction to exit the container

When the use exits the container. Then, we write the mic file from the repo zip configuration file

- [x] generates the MIC run file reading the .reprozip/config.yaml [issue](https://github.com/mintproject/mic/issues/144)
- [ ] copy the exposed files [issue](https://github.com/mintproject/mic/issues/148)
- [ ] Create a regex to find parameters in the invocation line [issue](https://github.com/mintproject/mic/issues/145)
- [x] Find the files in the working directory.  [issue](https://github.com/mintproject/mic/issues/146)
- [x] Detect outputs using the timestamp.

**Comment by dgarijo** [comment]
All right, then the new mic encapsulate step3 is the definition of inputs and parameters like we do it now?
